* Chapter 1
** Section 1-1

Exercize 1.3 isn't hard in the simple case, but I wonder if there's a
cleaner solution. Also, my solution doesn't gracefully handle equal
arguments.


Exercise 1.5 would be nice to talk through.

Exercise 1.6 could use some discussion. I think the answer has to do
with how things are evaluated, but I'm not sure.

Exercise 1.7 I have a working implementation, that works well for
small numbers, and actually returns for small numbers, but doesn't
work great for large numbers. This clearly has something to do with my
good-enough-change? function, but I'm not sure what.

** Section 1-2

Exercise 1.13 I got this working. I'm not sure if there's a better way
to do it though. Is it totally necessary to keep track of this many
steps back? Is there a way to generalize this for n steps of history?

Exercise 1.12 I'm not sure what this is even asking for.

Exercise 1.13 I'm skiping this proof.

** Section 1-3

I remember we spoke about 1.32, 1.33 and 1.42 - 1.44. Probably more
but that's what comes to mind

You should see if you can get 1.46. I didn't figure it out. Jackie had
to look up the answer. And I don't think anyone else got it.
* Chapter 2
** Section 2.2
Exercise 2.18 - This doesn't produce a list like I'm used to. Is there
a better way to do this?

Exercise 2.22 - I didn't do this, but I think it relates to my problem
above. Maybe talk about it?

Exercise 2.23 - I think my second solution still uses linear space,
can we make it iterative?

Exercise 2.24 - We should do this one the whiteboard
